config/routes.rb
Zen::Application.routes.draw do
  devise_for :users

  namespace :blog do
    resources :posts
  end

  get "store" => 'store#index'
  namespace :store do
    resources :leads
    resources :pages
    resources :items
    get "items/:id/(:page_id)" => "items#show"

  end

  root "blog/posts#index"
  

  

  

end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/blog/post.rb
class Blog::Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :route, use: [:finders]

  def cut_page
    /<cut\/>/.match(page)
    cut_page=$` || page
    cut_page.gsub!(/<%(.*)content_for(.*):title(.*)%>/, "")
    cut_page.gsub!(/<%(.*)content_for(.*):description(.*)%>/, "")
    cut_page
  end

  def uncut_page
    page.gsub("<cut/>", "")
  end

end

app/controllers/blog/posts_controller.rb
# -*- coding: utf-8 -*-

require 'my_erb'

class Blog::PostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show]
  # GET /blog/posts
  # GET /blog/posts.json
  def index
    @blog_posts = Blog::Post.order('created_at DESC').all
  end

  # GET /blog/posts/1
  # GET /blog/posts/1.json
  def show
    @crumbs[@blog_post.header]=@blog_post.route
  end

  # GET /blog/posts/new
  def new
    @blog_post = Blog::Post.new
  end

  # GET /blog/posts/1/edit
  def edit
  end

  # POST /blog/posts
  # POST /blog/posts.json
  def create
    @blog_post = Blog::Post.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog/posts/1
  # PATCH/PUT /blog/posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog/posts/1
  # DELETE /blog/posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = Blog::Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:header, :route, :tag, :page)
    end

    def set_layout_params
      super
      @path=request.path
      @crumbs['Блог']=blog_posts_path
    end
end

app/helpers/blog/posts_helper.rb
module Blog::PostsHelper
end

app/views/blog/posts/_form.html.erb
<%= form_for @blog_post, html:{class:"form"} do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :header %><br>
    <%= f.text_field :header %>
  </div>
  <div class="form-group">
    <%= f.label :route %><br>
    <%= f.text_field :route %>
  </div>
  <div class="form-group">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="form-group">
    <%= f.label :page %><br>
    <%= f.text_area :page, class:"form-control", rows: "30", cols: "100"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog/posts/_likes.html.erb
<div class="blog-post-likes">
  <!--<span><%=likes %></span>
  <%=image_tag('like.png')%> -->
</div> 

app/views/blog/posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog/posts/index.html.erb
<% content_for :description, "Блог, который помогает найти новинки, необычные вещи и уникальные подарки для себя, родных и близких." %>
<%= link_to 'Новый пост', new_blog_post_path if admin? %>
<div class="blog-posts-container">
  <div class="masonry-container">
    <% @blog_posts.each do |blog_post| %>
      <%@blog_post=blog_post #for ubiqitous context with show%>
    <div class="blog-post-container">
      <div class="blog-post-index-header">
	<h1><%= link_to blog_post.header, blog_post %></h1>
      </div>
      <div class="blog-post-index-time">
	<h6>
	  <small>
	    <%= blog_post.created_at.localtime.strftime("%d-%m-%Y")%>&nbsp;
	    <%= blog_post.created_at.localtime.strftime("%H:%M")%>
	  </small>
	</h6>
      </div>
      <div class="blog-post-index-page">
	<%=render_from_text(blog_post.cut_page, binding)%>
	<p><%= link_to "Подробнее", blog_post %></p>
	<%= render :partial => 'likes', locals:{likes:blog_post.likes} %>
      </div>
      <% if admin? %>
	<%= link_to "Правка", edit_blog_post_path(blog_post)%> |
	<%= link_to "Удалить", blog_post, method: :delete, data: { confirm: 'Are you sure?' }%>
      <% end %>
    </div>
  <% end %>
  </div>
</div>
<script>startMasonry('.masonry-container', '.blog-post-container');</script>

app/views/blog/posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog/posts/show.html.erb
<div class="blog-post-show-container">
  <div class="blog-post-index-header">
    <h2><%= @blog_post.header %></h2>
  </div>
  <div class="blog-post-index-time">
    <h6>
      <small>
	<%= @blog_post.created_at.localtime.strftime("%d-%m-%Y")%>&nbsp;
	<%= @blog_post.created_at.localtime.strftime("%H:%M")%>
      </small>
    </h6>
  </div>
  <div class="blog-post-show-page">
    <%=render_from_text(@blog_post.uncut_page, binding)%>
  </div>
  <%= render :partial => 'likes', locals:{likes:@blog_post.likes} %>
  <% if admin? %>
    <%= link_to "Правка", edit_blog_post_path(@blog_post)%> |
    <%= link_to "Удалить", @blog_post, method: :delete, data: { confirm: 'Are you sure?' }%>
  <% end %>
</div>