config/routes.rb
Zen::Application.routes.draw do
  devise_for :users

  namespace :blog do
    resources :posts
  end

  get "store" => 'store#index'
  namespace :store do
    resources :leads
    resources :pages
    resources :items
    get "items/:id/(:page_id)" => "items#show"

  end

  root "blog/posts#index"
  

  

  

end

app/views/shared/_breadcrumbs.html.erb
<ol class="breadcrumb">
  <% crumbs.each_with_index do |elem,index| %>
    <li class="<%= "active" if index == crumbs.length-1 %>">
      <%= link_to_if(index != crumbs.length-1, elem[0], elem[1] ) %>
    </li>
  <% end %>
</ol>

app/views/shared/_metrika.html.erb
<!-- Google analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44422310-2', 'teslablog.ru');
  ga('send', 'pageview');

  </script>
<!-- /Google analytics -->


<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter23199328 = new Ya.Metrika({id:23199328,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/23199328" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/shared/_navbar.html.erb
<div class="zen-navbar">
  <span class="zen-navbar-left">
    <%=image_tag 'logo.png'%>
    <span class="zen-navbar-header">
      <p class="zen-navbar-brand">Тесла</p>
      <p class="zen-navbar-brand-desc">Лучшие зарубежные новинки</p>
    </span>
  </span>
  <div class="zen-navbar-right">
    <table>
      <tr>
	<td class="<%=controller.controller_name=='posts' ? "active" : ""%>"><%= link_to 'Блог', blog_posts_path %></td>
	<td class="<%=controller.controller_name=='items' ? "active" : ""%>"><%= link_to 'Магазин', store_items_path %></td>
	<td class="<%=['sessions', 'registrations', 'passwords'].include?(controller.controller_name) ? "active" : ""%>"><%= user_signed_in? ? link_to('Выйти', destroy_user_session_path, method: :delete) : link_to('Войти', new_user_session_path) %></td>
      </tr>
    </table>
  </div>
</div>