config/routes.rb
Zen::Application.routes.draw do
  devise_for :users

  namespace :blog do
    resources :posts
  end

  get "store" => 'store#index'
  namespace :store do
    resources :leads
    resources :pages
    resources :items
    get "items/:id/(:page_id)" => "items#show"

  end

  root "blog/posts#index"
  

  

  

end

app/models/store.rb
module Store
  def self.table_name_prefix
    'store_'
  end
end

app/models/store/item.rb
class Store::Item < ActiveRecord::Base
  has_many :store_pages, class_name: "Store::Page", foreign_key: "store_item_id"
  extend FriendlyId
  friendly_id :route, use: [:finders]
end

app/models/store/lead.rb
class Store::Lead < ActiveRecord::Base
end

app/models/store/page.rb
class Store::Page < ActiveRecord::Base
  belongs_to :store_item, class_name: "Store::Item", foreign_key: "store_item_id"
  extend FriendlyId
  friendly_id :route, use: [:finders]
end

app/controllers/store/items_controller.rb
# -*- coding: utf-8 -*-
require 'my_erb'

class Store::ItemsController < ApplicationController

  before_action :set_store_item, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:show, :index]

  # GET /store/items
  # GET /store/items.json
  def index
    @store_items = Store::Item.all
  end

  # GET /store/items/1
  # GET /store/items/1.json
  def show
    @page=@store_item.store_pages.select {|item| item.route==(params[:page_id]||'')} [0]
    @lead=Store::Lead.new
    @crumbs[@store_item.name]=store_item_path(@store_item.route)
    @crumbs[@page.name]=store_item_path(@store_item.route)+"/#{@page.route}" if @page
  end

  # GET /store/items/new
  def new
    @store_item = Store::Item.new
  end

  # GET /store/items/1/edit
  def edit
  end

  # POST /store/items
  # POST /store/items.json
  def create
    @store_item = Store::Item.new(store_item_params)

    respond_to do |format|
      if @store_item.save
        format.html { redirect_to store_items_url+"/#{@store_item.route}", notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @store_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store/items/1
  # PATCH/PUT /store/items/1.json
  def update
    respond_to do |format|
      if @store_item.update(store_item_params)
        format.html { redirect_to store_items_url+"/#{@store_item.route}", notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store/items/1
  # DELETE /store/items/1.json
  def destroy
    @store_item.destroy
    respond_to do |format|
      format.html { redirect_to store_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_item
      @store_item = Store::Item.includes(:store_pages).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_item_params
      params.require(:store_item).permit(:name, :route, :group)
    end

    def set_layout_params
      super
      @crumbs['Магазин']=store_items_path
    end

end

app/controllers/store/leads_controller.rb
class Store::LeadsController < ApplicationController
  before_action :set_store_lead, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  # GET /store/leads
  # GET /store/leads.json
  def index
    @store_leads = Store::Lead.all
  end

  # GET /store/leads/1
  # GET /store/leads/1.json
  def show
  end

  # GET /store/leads/new
  def new
    @store_lead = Store::Lead.new
  end

  # GET /store/leads/1/edit
  def edit
  end

  # POST /store/leads
  # POST /store/leads.json
  def create
    @store_lead = Store::Lead.new(store_lead_params)

    respond_to do |format|
      if @store_lead.save
        format.html { redirect_to @store_lead, notice: 'Lead was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store_lead }
      else
        format.html { render action: 'new' }
        format.json { render json: @store_lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store/leads/1
  # PATCH/PUT /store/leads/1.json
  def update
    respond_to do |format|
      if @store_lead.update(store_lead_params)
        format.html { redirect_to @store_lead, notice: 'Lead was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store_lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store/leads/1
  # DELETE /store/leads/1.json
  def destroy
    @store_lead.destroy
    respond_to do |format|
      format.html { redirect_to store_leads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_lead
      @store_lead = Store::Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_lead_params
      params.require(:store_lead).permit(:name, :phone, :email, :address, :comments, :quantity, :color, :size, :aux, :item_id)
    end
end

app/controllers/store/pages_controller.rb
class Store::PagesController < ApplicationController
  before_action :set_store_page, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  # GET /store/pages
  # GET /store/pages.json
  def index
    @store_pages = Store::Page.all
  end

  # GET /store/pages/1
  # GET /store/pages/1.json
  def show
  end

  # GET /store/pages/new
  def new
    @store_page = Store::Page.new(store_item_id: params[:id])
    
  end

  # GET /store/pages/1/edit
  def edit
  end

  # POST /store/pages
  # POST /store/pages.json
  def create
    @store_page = Store::Page.new(store_page_params)

    respond_to do |format|
      if @store_page.save
        format.html { redirect_to @store_page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @store_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store/pages/1
  # PATCH/PUT /store/pages/1.json
  def update
    respond_to do |format|
      if @store_page.update(store_page_params)
        format.html { redirect_to @store_page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store/pages/1
  # DELETE /store/pages/1.json
  def destroy
    item=@store_page.store_item
    @store_page.destroy
    respond_to do |format|
      format.html { redirect_to store_item_path(item.route) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_page
      @store_page = Store::Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_page_params
      params.require(:store_page).permit(:name, :route, :html, :store_item_id)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
end

app/helpers/store/items_helper.rb
module Store::ItemsHelper
end

app/helpers/store/leads_helper.rb
module Store::LeadsHelper
end

app/helpers/store/pages_helper.rb
module Store::PagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/leads/_form.html.erb
<%= form_for(@store_lead) do |f| %>
  <% if @store_lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store_lead.errors.count, "error") %> prohibited this store_lead from being saved:</h2>

      <ul>
      <% @store_lead.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :aux %><br>
    <%= f.text_field :aux %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/store/leads/edit.html.erb
<h1>Editing store_lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @store_lead %> |
<%= link_to 'Back', store_leads_path %>

app/views/store/leads/index.html.erb
<h1>Listing store_leads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address</th>
      <th>Comments</th>
      <th>Quantity</th>
      <th>Color</th>
      <th>Size</th>
      <th>Aux</th>
      <th>Item</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @store_leads.each do |store_lead| %>
      <tr>
        <td><%= store_lead.name %></td>
        <td><%= store_lead.phone %></td>
        <td><%= store_lead.email %></td>
        <td><%= store_lead.address %></td>
        <td><%= store_lead.comments %></td>
        <td><%= store_lead.quantity %></td>
        <td><%= store_lead.color %></td>
        <td><%= store_lead.size %></td>
        <td><%= store_lead.aux %></td>
        <td><%= store_lead.item_id %></td>
        <td><%= link_to 'Show', store_lead %></td>
        <td><%= link_to 'Edit', edit_store_lead_path(store_lead) if admin? %></td>
        <td><%= link_to 'Destroy', store_lead, method: :delete, data: { confirm: 'Are you sure?' } if admin?%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_store_lead_path %>

app/views/store/leads/new.html.erb
<h1>New store_lead</h1>

<%= render 'form' %>

<%= link_to 'Back', store_leads_path %>

app/views/store/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store_lead.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store_lead.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @store_lead.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store_lead.address %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @store_lead.comments %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @store_lead.quantity %>
</p>

<p>
  <strong>Color:</strong>
  <%= @store_lead.color %>
</p>

<p>
  <strong>Size:</strong>
  <%= @store_lead.size %>
</p>

<p>
  <strong>Aux:</strong>
  <%= @store_lead.aux %>
</p>

<p>
  <strong>Item:</strong>
  <%= @store_lead.item_id %>
</p>

<%= link_to 'Edit', edit_store_lead_path(@store_lead) %> |
<%= link_to 'Back', store_leads_path %>